CC=g++
CFLAGS=-std=c++17 -O3 -march=native
OUT=reversi
SRC_PATH=./
OUT_PATH=../bin/

debug:
	g++ -g reversi10.cpp -o $(OUT)

one:
	$(CC) $(CFLAGS) $(SRC_PATH)reversi.cpp -o $(OUT_PATH)$(OUT)-mk1

two:
	$(CC) $(CFLAGS) $(SRC_PATH)reversi2.cpp -o $(OUT_PATH)$(OUT)-mk2

three:
	$(CC) $(CFLAGS) $(SRC_PATH)reversi3.cpp -o $(OUT_PATH)$(OUT)-mk3

four:
	$(CC) $(CFLAGS) $(SRC_PATH)reversi4.cpp -o $(OUT_PATH)$(OUT)-mk4

five:
	$(CC) $(CFLAGS) $(SRC_PATH)reversi5.cpp -o $(OUT_PATH)$(OUT)-mk5

six:
	$(CC) $(CFLAGS) $(SRC_PATH)reversi6.cpp -o $(OUT_PATH)$(OUT)-mk6

seven:
	$(CC) $(CFLAGS) $(SRC_PATH)reversi7.cpp -o $(OUT_PATH)$(OUT)-mk7

eight:
	$(CC) $(CFLAGS) $(SRC_PATH)reversi8.cpp -o $(OUT_PATH)$(OUT)-mk8

nine:
	$(CC) $(CFLAGS) $(SRC_PATH)reversi9.cpp -o $(OUT_PATH)$(OUT)-mk9

ten:
	$(CC) $(CFLAGS) $(SRC_PATH)reversi10.cpp -o $(OUT_PATH)$(OUT)-mk10

